# Cascade Classifier

Ca sa pot sa incep am nevie de 2 seturi de imagini, un set pozitiv(cu fete) si un set negativ(care nu are fete).

![](figs/faces.png)

To create a personal detector we must download images from internet and send the images a machine learning alghorithm called AdaBoost Training. This alghorithm will select the features of the images. Each square image shows what exactly they are, which are little white and black square with different shapes. The idea is to apply each of this square in the image to each sub-window of the image. (Will g from the left to right) ( I can consider the black points as the 1, when is is found, and the withe as 0, when it is not found)

![](figs/FeatureSelction.png)

Basics equasion: Sum of white pixels - sum of black pixels.

<br>

For example: 

<br>

if we have 24 pixels white pixels and 24 black pixels that means we have more than 160.000 combination to apply to that image.

The ideea of putting the features into the image is called sliding window. After the small squares will finish filling the image we will apply the equasion. At the end we will have a matrix of numbers, similar to:

<br>

2 3 5 6
<br>
8 9 2 1
<br>

The name of the classifier is called cascade, because we are going from top to bottom of the image.

![](figs/Classifiers.png)

For example we have the red spot and that can be the algorithm to find the eyes the black pixels is on the eye.

After the alghorithm is trained we have another stage called _Cascade_, which is the process to clasify the image( to detect the object/face)

![](figs/Cascade.png)

The image is getting and each _C_ represents a classifiers( are those features, squares). If feature 1 does not exist will terminate the and return _No Detection_. If the feature1 exist then will go to feature2. If a single feature does not exist the alghorithm will retuen _No Detection_.

# Implementation

>Loading the image

In [1]:
import cv2 as cv

frame = cv.imread('./imgs/people.jpg') # read the image
frame.shape # see the parameters of the image

cv.imshow('test',frame) # show the image

   QT_AUTO_SCREEN_SCALE_FACTOR to enable platform plugin controlled per-screen factors.
   QT_SCREEN_SCALE_FACTORS to set per-screen DPI.
   QT_SCALE_FACTOR to set the application global scale factor.


>Detecting faces

In [2]:
face_detector = cv.CascadeClassifier('../haarcascades/haarcascade_frontalface_default.xml') # create object for CascadeClassifier 
                                                                                           # for recognising frontal faces

frame = cv.imread('./imgs/people.jpg') # read the image
frame.shape # see the parameters of the image

detection = face_detector.detectMultiScale(frame) # create an object for the processed image
print(detection)
len(detection)

[[1250  212  254  254]
 [ 539  281  291  291]
 [1354  497   62   62]
 [ 784  544  304  304]
 [ 996  550  290  290]
 [ 251  608  324  324]]


6

In [3]:
for(x,y,w,h) in detection: #create a for that will traverse the detection object
    print(x,y,w,h)

1250 212 254 254
539 281 291 291
1354 497 62 62
784 544 304 304
996 550 290 290
251 608 324 324


: 

In [ ]:
for(x,y,w,h) in detection: #create a for that will traverse the detection object
    #             the image(original)      where the rectangle starts       where the rectangle terminates     color in BGR         tichness   
    cv.rectangle(       frame,                          (x,y),                      (x,y),                          (0,255,0),          2) # drow the rectangle

cv.imshow('a',frame)
# for a dot

In [ ]:
for(x,y,w,h) in detection: #create a for that will traverse the detection object
    #             the image(original)      where the rectangle starts       where the rectangle terminates     color in BGR         tichness   
    cv.rectangle(       frame,                          (x+w,y),                      (x,y),                          (0,255,0),          2) # drow the rectangle

cv.imshow('a',frame)
# for a line

In [ ]:
for(x,y,w,h) in detection: #create a for that will traverse the detection object
    #             the image(original)      where the rectangle starts       where the rectangle terminates     color in BGR         tichness   
    cv.rectangle(       frame,                          (x+w,y+h),                      (x,y),                          (0,255,0),          2) # drow the rectangle

cv.imshow('a',frame)
# for a rectangle

>Haarcascade parameters

>> ScaleFactor

Scale parameter is used to automaticallyscale the image. For instance in the previous example we had an error, a face was detected where no face was. The default scale is 1.1, we are not allowed to scale less than 1. If we will put 1.01 more faces(errors will appear).  If we will put it more, for instance 1.5 some faces will not be detected.
<br>
The scale must be put it in concordance with the image. If we have small images the scale will be small. If we have large images the scale will be large.

The errors are called false positives.

>> minNeighbors

Is kind of the opposite of ScaleFactor

We have to choose if we want to have more quanti or more detection

>> minSize

The default value is 30x30

Minimum value of the box

>> maxSize

The maximum value of the box

Eye detection

Create an object for the prebuild classifier for eyes.

<br>

Make the same for loop for drowing the rectangles, but now for eyes.

In [ ]:
eye_detect = eye_detection.detectMultiScale(frame)

for (x, y, w, h) in eye_detect:
    cv.rectangle(frame,(x,y),(x+w,y+h),(0,0,255),2)

We can also put the scale factor, as well, but can give as true positive results.